[2022-04-28 06:05:07,496] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [queued]>
[2022-04-28 06:05:07,540] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [queued]>
[2022-04-28 06:05:07,542] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 06:05:07,544] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-28 06:05:07,545] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 06:05:07,595] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2001-01-01 00:00:00+00:00
[2022-04-28 06:05:07,604] {standard_task_runner.py:52} INFO - Started process 1736 to run task
[2022-04-28 06:05:07,612] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2001-01-01T00:00:00+00:00', '--job-id', '529', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpcgfpaxgh', '--error-file', '/tmp/tmpop5ew2x4']
[2022-04-28 06:05:07,616] {standard_task_runner.py:80} INFO - Job 529: Subtask local_to_gcs_task
[2022-04-28 06:05:08,008] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [running]> on host d4721d223bdd
[2022-04-28 06:05:08,368] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-28 06:05:08,554] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2001-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2001-01-01T00:00:00+00:00
[2022-04-28 06:05:10,145] {python.py:175} INFO - Done. Returned value was: None
[2022-04-28 06:05:10,311] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20010101T000000, start_date=20220428T060507, end_date=20220428T060510
[2022-04-28 06:05:10,393] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-28 06:05:10,754] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-29 02:35:49,955] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [queued]>
[2022-04-29 02:35:50,004] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [queued]>
[2022-04-29 02:35:50,006] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 02:35:50,007] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-29 02:35:50,009] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 02:35:50,055] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2001-01-01 00:00:00+00:00
[2022-04-29 02:35:50,065] {standard_task_runner.py:52} INFO - Started process 5367 to run task
[2022-04-29 02:35:50,073] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2001-01-01T00:00:00+00:00', '--job-id', '708', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpmhwn36j3', '--error-file', '/tmp/tmpf5o82mm9']
[2022-04-29 02:35:50,077] {standard_task_runner.py:80} INFO - Job 708: Subtask local_to_gcs_task
[2022-04-29 02:35:50,467] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [running]> on host 6fd0ba274d58
[2022-04-29 02:35:50,718] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-29 02:35:50,913] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2001-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2001-01-01T00:00:00+00:00
[2022-04-29 02:35:52,342] {python.py:175} INFO - Done. Returned value was: None
[2022-04-29 02:35:52,552] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20010101T000000, start_date=20220429T023549, end_date=20220429T023552
[2022-04-29 02:35:52,626] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-29 02:35:52,872] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-02 07:54:34,975] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [queued]>
[2022-05-02 07:54:35,022] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [queued]>
[2022-05-02 07:54:35,024] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 07:54:35,026] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 07:54:35,028] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 07:54:35,073] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2001-01-01 00:00:00+00:00
[2022-05-02 07:54:35,082] {standard_task_runner.py:52} INFO - Started process 9245 to run task
[2022-05-02 07:54:35,090] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2001-01-01T00:00:00+00:00', '--job-id', '856', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmp9croke_f', '--error-file', '/tmp/tmppqx2noau']
[2022-05-02 07:54:35,093] {standard_task_runner.py:77} INFO - Job 856: Subtask local_to_gcs_task
[2022-05-02 07:54:35,487] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [running]> on host ae42322ae538
[2022-05-02 07:54:35,751] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 07:54:35,942] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2001-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2001-01-01T00:00:00+00:00
[2022-05-02 07:54:36,737] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 07:54:36,838] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20010101T000000, start_date=20220502T075434, end_date=20220502T075436
[2022-05-02 07:54:36,917] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 07:54:37,158] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 09:16:41,684] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [queued]>
[2022-05-02 09:16:41,723] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [queued]>
[2022-05-02 09:16:41,724] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 09:16:41,726] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 09:16:41,727] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 09:16:41,764] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2001-01-01 00:00:00+00:00
[2022-05-02 09:16:41,773] {standard_task_runner.py:52} INFO - Started process 2507 to run task
[2022-05-02 09:16:41,781] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2001-01-01T00:00:00+00:00', '--job-id', '976', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpolrfbiz8', '--error-file', '/tmp/tmp5g253rt0']
[2022-05-02 09:16:41,783] {standard_task_runner.py:77} INFO - Job 976: Subtask local_to_gcs_task
[2022-05-02 09:16:42,146] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [running]> on host 98c324cf1bb6
[2022-05-02 09:16:42,388] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 09:16:42,561] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2001-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2001-01-01T00:00:00+00:00
[2022-05-02 09:16:43,258] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 09:16:43,363] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20010101T000000, start_date=20220502T091641, end_date=20220502T091643
[2022-05-02 09:16:43,439] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 09:16:43,654] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 15:57:45,385] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [queued]>
[2022-05-02 15:57:45,427] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [queued]>
[2022-05-02 15:57:45,428] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 15:57:45,429] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 15:57:45,430] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 15:57:45,481] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2001-01-01 00:00:00+00:00
[2022-05-02 15:57:45,496] {standard_task_runner.py:52} INFO - Started process 1644 to run task
[2022-05-02 15:57:45,508] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2001-01-01T00:00:00+00:00', '--job-id', '1077', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpypp3t5ki', '--error-file', '/tmp/tmphvm6nzhn']
[2022-05-02 15:57:45,511] {standard_task_runner.py:77} INFO - Job 1077: Subtask local_to_gcs_task
[2022-05-02 15:57:45,878] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [running]> on host 9f5021834e17
[2022-05-02 15:57:46,119] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 15:57:46,303] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2001-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2001-01-01T00:00:00+00:00
[2022-05-02 15:57:47,057] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 15:57:47,188] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20010101T000000, start_date=20220502T155745, end_date=20220502T155747
[2022-05-02 15:57:47,271] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 15:57:47,523] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 16:32:45,827] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:32:45,875] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:32:45,876] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:32:45,878] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 16:32:45,879] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:32:45,926] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2001-01-01 00:00:00+00:00
[2022-05-02 16:32:45,939] {standard_task_runner.py:52} INFO - Started process 6206 to run task
[2022-05-02 16:32:45,948] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2001-01-01T00:00:00+00:00', '--job-id', '1183', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmplcwrp6wf', '--error-file', '/tmp/tmpa338kuq8']
[2022-05-02 16:32:45,952] {standard_task_runner.py:77} INFO - Job 1183: Subtask local_to_gcs_task
[2022-05-02 16:32:46,333] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [running]> on host 9f5021834e17
[2022-05-02 16:32:46,589] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 16:32:46,784] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2001-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2001-01-01T00:00:00+00:00
[2022-05-02 16:32:47,549] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 16:32:47,689] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20010101T000000, start_date=20220502T163245, end_date=20220502T163247
[2022-05-02 16:32:47,752] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 16:32:47,976] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 16:48:21,630] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:48:21,672] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:48:21,674] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:48:21,676] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 16:48:21,677] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:48:21,716] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2001-01-01 00:00:00+00:00
[2022-05-02 16:48:21,725] {standard_task_runner.py:52} INFO - Started process 9036 to run task
[2022-05-02 16:48:21,733] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2001-01-01T00:00:00+00:00', '--job-id', '1288', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpd4wd81nb', '--error-file', '/tmp/tmpi3jlwx2n']
[2022-05-02 16:48:21,735] {standard_task_runner.py:77} INFO - Job 1288: Subtask local_to_gcs_task
[2022-05-02 16:48:22,080] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2001-01-01T00:00:00+00:00 [running]> on host 9f5021834e17
[2022-05-02 16:48:22,303] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 16:48:22,479] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2001-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2001-01-01T00:00:00+00:00
[2022-05-02 16:48:23,290] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 16:48:23,402] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20010101T000000, start_date=20220502T164821, end_date=20220502T164823
[2022-05-02 16:48:23,480] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 16:48:23,685] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
