[2022-04-28 06:06:36,751] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-04-28 06:06:36,794] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-04-28 06:06:36,795] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 06:06:36,796] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-28 06:06:36,797] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 06:06:36,837] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2004-01-01 00:00:00+00:00
[2022-04-28 06:06:36,847] {standard_task_runner.py:52} INFO - Started process 2070 to run task
[2022-04-28 06:06:36,856] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2004-01-01T00:00:00+00:00', '--job-id', '549', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpvkr3mju9', '--error-file', '/tmp/tmpobx8yoa4']
[2022-04-28 06:06:36,861] {standard_task_runner.py:80} INFO - Job 549: Subtask local_to_gcs_task
[2022-04-28 06:06:37,255] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [running]> on host d4721d223bdd
[2022-04-28 06:06:37,564] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-28 06:06:37,762] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2004-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2004-01-01T00:00:00+00:00
[2022-04-28 06:06:39,216] {python.py:175} INFO - Done. Returned value was: None
[2022-04-28 06:06:39,319] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20040101T000000, start_date=20220428T060636, end_date=20220428T060639
[2022-04-28 06:06:39,400] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-28 06:06:39,665] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-04-29 02:36:43,449] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-04-29 02:36:43,495] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-04-29 02:36:43,496] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 02:36:43,497] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-29 02:36:43,498] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 02:36:43,549] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2004-01-01 00:00:00+00:00
[2022-04-29 02:36:43,560] {standard_task_runner.py:52} INFO - Started process 5556 to run task
[2022-04-29 02:36:43,568] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2004-01-01T00:00:00+00:00', '--job-id', '719', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpcb09uxx1', '--error-file', '/tmp/tmp6vd9d47i']
[2022-04-29 02:36:43,572] {standard_task_runner.py:80} INFO - Job 719: Subtask local_to_gcs_task
[2022-04-29 02:36:43,965] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [running]> on host 6fd0ba274d58
[2022-04-29 02:36:44,231] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-29 02:36:44,447] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2004-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2004-01-01T00:00:00+00:00
[2022-04-29 02:36:45,801] {python.py:175} INFO - Done. Returned value was: None
[2022-04-29 02:36:45,916] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20040101T000000, start_date=20220429T023643, end_date=20220429T023645
[2022-04-29 02:36:45,984] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-29 02:36:46,759] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 07:55:40,421] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-05-02 07:55:40,465] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-05-02 07:55:40,467] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 07:55:40,468] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 07:55:40,470] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 07:55:40,516] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2004-01-01 00:00:00+00:00
[2022-05-02 07:55:40,525] {standard_task_runner.py:52} INFO - Started process 9476 to run task
[2022-05-02 07:55:40,533] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2004-01-01T00:00:00+00:00', '--job-id', '868', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpbdn5se8v', '--error-file', '/tmp/tmp9hf3jcgo']
[2022-05-02 07:55:40,536] {standard_task_runner.py:77} INFO - Job 868: Subtask local_to_gcs_task
[2022-05-02 07:55:40,902] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [running]> on host ae42322ae538
[2022-05-02 07:55:41,154] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 07:55:41,347] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2004-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2004-01-01T00:00:00+00:00
[2022-05-02 07:55:42,180] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 07:55:42,284] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20040101T000000, start_date=20220502T075540, end_date=20220502T075542
[2022-05-02 07:55:42,355] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 07:55:42,570] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 09:17:46,461] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-05-02 09:17:46,510] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-05-02 09:17:46,512] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 09:17:46,514] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 09:17:46,516] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 09:17:46,564] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2004-01-01 00:00:00+00:00
[2022-05-02 09:17:46,574] {standard_task_runner.py:52} INFO - Started process 2748 to run task
[2022-05-02 09:17:46,589] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2004-01-01T00:00:00+00:00', '--job-id', '987', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpjab11dkt', '--error-file', '/tmp/tmpg70lf2mb']
[2022-05-02 09:17:46,592] {standard_task_runner.py:77} INFO - Job 987: Subtask local_to_gcs_task
[2022-05-02 09:17:47,024] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [running]> on host 98c324cf1bb6
[2022-05-02 09:17:47,522] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 09:17:47,798] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2004-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2004-01-01T00:00:00+00:00
[2022-05-02 09:17:48,567] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 09:17:48,671] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20040101T000000, start_date=20220502T091746, end_date=20220502T091748
[2022-05-02 09:17:48,761] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 09:17:49,118] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 15:58:43,860] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-05-02 15:58:43,914] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-05-02 15:58:43,915] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 15:58:43,917] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 15:58:43,918] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 15:58:43,966] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2004-01-01 00:00:00+00:00
[2022-05-02 15:58:43,982] {standard_task_runner.py:52} INFO - Started process 1875 to run task
[2022-05-02 15:58:43,996] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2004-01-01T00:00:00+00:00', '--job-id', '1088', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpyza9335k', '--error-file', '/tmp/tmps3drvcu6']
[2022-05-02 15:58:43,999] {standard_task_runner.py:77} INFO - Job 1088: Subtask local_to_gcs_task
[2022-05-02 15:58:44,363] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [running]> on host 9f5021834e17
[2022-05-02 15:58:44,595] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 15:58:44,781] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2004-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2004-01-01T00:00:00+00:00
[2022-05-02 15:58:45,693] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 15:58:45,798] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20040101T000000, start_date=20220502T155843, end_date=20220502T155845
[2022-05-02 15:58:45,878] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 15:58:46,096] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 16:33:52,733] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:33:52,789] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:33:52,791] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:33:52,794] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 16:33:52,795] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:33:52,850] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2004-01-01 00:00:00+00:00
[2022-05-02 16:33:52,862] {standard_task_runner.py:52} INFO - Started process 6455 to run task
[2022-05-02 16:33:52,875] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2004-01-01T00:00:00+00:00', '--job-id', '1195', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmp50df_4v_', '--error-file', '/tmp/tmpnyj11aq6']
[2022-05-02 16:33:52,878] {standard_task_runner.py:77} INFO - Job 1195: Subtask local_to_gcs_task
[2022-05-02 16:33:53,284] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [running]> on host 9f5021834e17
[2022-05-02 16:33:53,589] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 16:33:53,803] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2004-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2004-01-01T00:00:00+00:00
[2022-05-02 16:33:54,625] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 16:33:54,762] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20040101T000000, start_date=20220502T163352, end_date=20220502T163354
[2022-05-02 16:33:54,837] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 16:33:55,076] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 16:49:26,278] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:49:26,320] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:49:26,321] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:49:26,323] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 16:49:26,324] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:49:26,364] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2004-01-01 00:00:00+00:00
[2022-05-02 16:49:26,375] {standard_task_runner.py:52} INFO - Started process 9264 to run task
[2022-05-02 16:49:26,383] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2004-01-01T00:00:00+00:00', '--job-id', '1300', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmp7_uwphoa', '--error-file', '/tmp/tmp6e4330eh']
[2022-05-02 16:49:26,385] {standard_task_runner.py:77} INFO - Job 1300: Subtask local_to_gcs_task
[2022-05-02 16:49:26,735] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2004-01-01T00:00:00+00:00 [running]> on host 9f5021834e17
[2022-05-02 16:49:26,975] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 16:49:27,186] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2004-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2004-01-01T00:00:00+00:00
[2022-05-02 16:49:28,104] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 16:49:28,231] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20040101T000000, start_date=20220502T164926, end_date=20220502T164928
[2022-05-02 16:49:28,314] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 16:49:28,536] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
