[2022-04-28 04:16:09,947] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [queued]>
[2022-04-28 04:16:09,993] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [queued]>
[2022-04-28 04:16:09,994] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 04:16:09,995] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-28 04:16:09,997] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 04:16:10,048] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): format_xl_to_csv_task> on 1994-01-01 00:00:00+00:00
[2022-04-28 04:16:10,058] {standard_task_runner.py:52} INFO - Started process 3621 to run task
[2022-04-28 04:16:10,065] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'format_xl_to_csv_task', 'scheduled__1994-01-01T00:00:00+00:00', '--job-id', '408', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpf4r76b85', '--error-file', '/tmp/tmpcyuth0bg']
[2022-04-28 04:16:10,069] {standard_task_runner.py:80} INFO - Job 408: Subtask format_xl_to_csv_task
[2022-04-28 04:16:10,441] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [running]> on host 65f5b8b3c17c
[2022-04-28 04:16:10,763] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-28 04:16:11,030] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=format_xl_to_csv_task
AIRFLOW_CTX_EXECUTION_DATE=1994-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__1994-01-01T00:00:00+00:00
[2022-04-28 04:16:16,797] {python.py:175} INFO - Done. Returned value was: None
[2022-04-28 04:16:16,904] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=format_xl_to_csv_task, execution_date=19940101T000000, start_date=20220428T041609, end_date=20220428T041616
[2022-04-28 04:16:16,987] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-28 04:16:17,279] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-04-28 05:36:33,825] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [queued]>
[2022-04-28 05:36:33,872] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [queued]>
[2022-04-28 05:36:33,874] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 05:36:33,875] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-28 05:36:33,876] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 05:36:33,927] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): format_xl_to_csv_task> on 1994-01-01 00:00:00+00:00
[2022-04-28 05:36:33,938] {standard_task_runner.py:52} INFO - Started process 6202 to run task
[2022-04-28 05:36:33,951] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'format_xl_to_csv_task', 'scheduled__1994-01-01T00:00:00+00:00', '--job-id', '454', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmporsi7g5p', '--error-file', '/tmp/tmpjrk6w77x']
[2022-04-28 05:36:33,954] {standard_task_runner.py:80} INFO - Job 454: Subtask format_xl_to_csv_task
[2022-04-28 05:36:34,292] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [running]> on host 65f5b8b3c17c
[2022-04-28 05:36:34,519] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-28 05:36:34,706] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=format_xl_to_csv_task
AIRFLOW_CTX_EXECUTION_DATE=1994-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__1994-01-01T00:00:00+00:00
[2022-04-28 05:36:40,663] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_to_gcs_dag.py", line 58, in format_xl_to_csv
    df.to_csv(f"{AIRFLOW_HOME}/us_employment_{df.year(6)}.csv")
TypeError: 'Series' object is not callable
[2022-04-28 05:36:40,773] {taskinstance.py:1288} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcp_dag, task_id=format_xl_to_csv_task, execution_date=19940101T000000, start_date=20220428T053633, end_date=20220428T053640
[2022-04-28 05:36:40,996] {standard_task_runner.py:98} ERROR - Failed to execute job 454 for task format_xl_to_csv_task ('Series' object is not callable; 6202)
[2022-04-28 05:36:41,022] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-28 05:36:41,298] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-28 06:02:32,081] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [queued]>
[2022-04-28 06:02:32,130] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [queued]>
[2022-04-28 06:02:32,132] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 06:02:32,134] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-28 06:02:32,136] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 06:02:32,188] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): format_xl_to_csv_task> on 1994-01-01 00:00:00+00:00
[2022-04-28 06:02:32,198] {standard_task_runner.py:52} INFO - Started process 1186 to run task
[2022-04-28 06:02:32,208] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'format_xl_to_csv_task', 'scheduled__1994-01-01T00:00:00+00:00', '--job-id', '495', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpvxmz3jle', '--error-file', '/tmp/tmpzawo7e0m']
[2022-04-28 06:02:32,211] {standard_task_runner.py:80} INFO - Job 495: Subtask format_xl_to_csv_task
[2022-04-28 06:02:32,578] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [running]> on host d4721d223bdd
[2022-04-28 06:02:32,834] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-28 06:02:33,020] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=format_xl_to_csv_task
AIRFLOW_CTX_EXECUTION_DATE=1994-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__1994-01-01T00:00:00+00:00
[2022-04-28 06:02:38,578] {python.py:175} INFO - Done. Returned value was: None
[2022-04-28 06:02:38,686] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=format_xl_to_csv_task, execution_date=19940101T000000, start_date=20220428T060232, end_date=20220428T060238
[2022-04-28 06:02:38,787] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-28 06:02:39,058] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-04-29 02:29:08,948] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [queued]>
[2022-04-29 02:29:08,991] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [queued]>
[2022-04-29 02:29:08,992] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 02:29:08,993] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-29 02:29:08,994] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 02:29:09,038] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): format_xl_to_csv_task> on 1994-01-01 00:00:00+00:00
[2022-04-29 02:29:09,048] {standard_task_runner.py:52} INFO - Started process 4296 to run task
[2022-04-29 02:29:09,056] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'format_xl_to_csv_task', 'scheduled__1994-01-01T00:00:00+00:00', '--job-id', '659', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmp_lv9vz1t', '--error-file', '/tmp/tmpqal4zyc1']
[2022-04-29 02:29:09,059] {standard_task_runner.py:80} INFO - Job 659: Subtask format_xl_to_csv_task
[2022-04-29 02:29:09,424] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [running]> on host 6fd0ba274d58
[2022-04-29 02:29:09,662] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-29 02:29:09,873] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=format_xl_to_csv_task
AIRFLOW_CTX_EXECUTION_DATE=1994-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__1994-01-01T00:00:00+00:00
[2022-04-29 02:29:15,819] {python.py:175} INFO - Done. Returned value was: None
[2022-04-29 02:29:15,947] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=format_xl_to_csv_task, execution_date=19940101T000000, start_date=20220429T022908, end_date=20220429T022915
[2022-04-29 02:29:16,049] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-29 02:29:16,564] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-29 02:31:40,687] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [queued]>
[2022-04-29 02:31:40,741] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [queued]>
[2022-04-29 02:31:40,743] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 02:31:40,747] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-29 02:31:40,749] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 02:31:40,803] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): format_xl_to_csv_task> on 1994-01-01 00:00:00+00:00
[2022-04-29 02:31:40,814] {standard_task_runner.py:52} INFO - Started process 4708 to run task
[2022-04-29 02:31:40,823] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'format_xl_to_csv_task', 'scheduled__1994-01-01T00:00:00+00:00', '--job-id', '677', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmp7w171kxm', '--error-file', '/tmp/tmpp9v32ri0']
[2022-04-29 02:31:40,829] {standard_task_runner.py:80} INFO - Job 677: Subtask format_xl_to_csv_task
[2022-04-29 02:31:41,258] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [running]> on host 6fd0ba274d58
[2022-04-29 02:31:41,592] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-29 02:31:41,845] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=format_xl_to_csv_task
AIRFLOW_CTX_EXECUTION_DATE=1994-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__1994-01-01T00:00:00+00:00
[2022-04-29 02:31:47,899] {python.py:175} INFO - Done. Returned value was: None
[2022-04-29 02:31:48,004] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=format_xl_to_csv_task, execution_date=19940101T000000, start_date=20220429T023140, end_date=20220429T023148
[2022-04-29 02:31:48,072] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-29 02:31:48,316] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-02 07:52:46,786] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [queued]>
[2022-05-02 07:52:46,830] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [queued]>
[2022-05-02 07:52:46,832] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 07:52:46,833] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 07:52:46,834] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 07:52:46,882] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_xl_to_csv_task> on 1994-01-01 00:00:00+00:00
[2022-05-02 07:52:46,892] {standard_task_runner.py:52} INFO - Started process 8842 to run task
[2022-05-02 07:52:46,907] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'format_xl_to_csv_task', 'scheduled__1994-01-01T00:00:00+00:00', '--job-id', '837', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpkoinj5eu', '--error-file', '/tmp/tmpeb3hhpmr']
[2022-05-02 07:52:46,910] {standard_task_runner.py:77} INFO - Job 837: Subtask format_xl_to_csv_task
[2022-05-02 07:52:47,271] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [running]> on host ae42322ae538
[2022-05-02 07:52:47,501] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 07:52:47,682] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=format_xl_to_csv_task
AIRFLOW_CTX_EXECUTION_DATE=1994-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__1994-01-01T00:00:00+00:00
[2022-05-02 07:52:53,269] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 07:52:53,467] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=format_xl_to_csv_task, execution_date=19940101T000000, start_date=20220502T075246, end_date=20220502T075253
[2022-05-02 07:52:53,554] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 07:52:53,787] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-02 09:14:48,439] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [queued]>
[2022-05-02 09:14:48,484] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [queued]>
[2022-05-02 09:14:48,486] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 09:14:48,488] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 09:14:48,489] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 09:14:48,533] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_xl_to_csv_task> on 1994-01-01 00:00:00+00:00
[2022-05-02 09:14:48,542] {standard_task_runner.py:52} INFO - Started process 2117 to run task
[2022-05-02 09:14:48,550] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'format_xl_to_csv_task', 'scheduled__1994-01-01T00:00:00+00:00', '--job-id', '955', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmp82vo19h_', '--error-file', '/tmp/tmp4v8cqe_3']
[2022-05-02 09:14:48,552] {standard_task_runner.py:77} INFO - Job 955: Subtask format_xl_to_csv_task
[2022-05-02 09:14:48,926] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__1994-01-01T00:00:00+00:00 [running]> on host 98c324cf1bb6
[2022-05-02 09:14:49,228] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 09:14:49,440] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=format_xl_to_csv_task
AIRFLOW_CTX_EXECUTION_DATE=1994-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__1994-01-01T00:00:00+00:00
[2022-05-02 09:14:55,758] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 09:14:56,183] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=format_xl_to_csv_task, execution_date=19940101T000000, start_date=20220502T091448, end_date=20220502T091456
[2022-05-02 09:14:56,267] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 09:14:56,502] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
