[2022-04-28 06:13:59,288] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2022-04-28 06:13:59,328] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2022-04-28 06:13:59,329] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 06:13:59,331] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-28 06:13:59,332] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 06:13:59,371] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-01-01 00:00:00+00:00
[2022-04-28 06:13:59,381] {standard_task_runner.py:52} INFO - Started process 3445 to run task
[2022-04-28 06:13:59,388] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '624', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpexxu7f_7', '--error-file', '/tmp/tmp3ib6awq9']
[2022-04-28 06:13:59,392] {standard_task_runner.py:80} INFO - Job 624: Subtask local_to_gcs_task
[2022-04-28 06:13:59,751] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [running]> on host d4721d223bdd
[2022-04-28 06:14:00,013] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-28 06:14:00,203] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2022-04-28 06:14:01,585] {python.py:175} INFO - Done. Returned value was: None
[2022-04-28 06:14:01,690] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20210101T000000, start_date=20220428T061359, end_date=20220428T061401
[2022-04-28 06:14:01,774] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-28 06:14:01,995] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-04-29 02:41:09,303] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2022-04-29 02:41:09,349] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2022-04-29 02:41:09,351] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 02:41:09,352] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-29 02:41:09,353] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 02:41:09,400] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-01-01 00:00:00+00:00
[2022-04-29 02:41:09,410] {standard_task_runner.py:52} INFO - Started process 6694 to run task
[2022-04-29 02:41:09,419] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '790', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpybp5sbxk', '--error-file', '/tmp/tmprz4j50gi']
[2022-04-29 02:41:09,422] {standard_task_runner.py:80} INFO - Job 790: Subtask local_to_gcs_task
[2022-04-29 02:41:09,798] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [running]> on host 6fd0ba274d58
[2022-04-29 02:41:10,027] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-29 02:41:10,205] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2022-04-29 02:41:12,029] {python.py:175} INFO - Done. Returned value was: None
[2022-04-29 02:41:12,264] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20210101T000000, start_date=20220429T024109, end_date=20220429T024112
[2022-04-29 02:41:12,356] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-29 02:41:12,574] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-02 07:59:04,095] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2022-05-02 07:59:04,170] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2022-05-02 07:59:04,172] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 07:59:04,173] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 07:59:04,175] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 07:59:04,237] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-01-01 00:00:00+00:00
[2022-05-02 07:59:04,267] {standard_task_runner.py:52} INFO - Started process 10326 to run task
[2022-05-02 07:59:04,325] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '918', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpqu38kch_', '--error-file', '/tmp/tmp8dhzxg2s']
[2022-05-02 07:59:04,342] {standard_task_runner.py:77} INFO - Job 918: Subtask local_to_gcs_task
[2022-05-02 07:59:05,241] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [running]> on host ae42322ae538
[2022-05-02 07:59:05,770] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 07:59:06,071] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2022-05-02 07:59:06,853] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 07:59:06,955] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20210101T000000, start_date=20220502T075904, end_date=20220502T075906
[2022-05-02 07:59:07,033] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 07:59:07,253] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 09:20:56,228] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2022-05-02 09:20:56,269] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2022-05-02 09:20:56,270] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 09:20:56,272] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 09:20:56,273] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 09:20:56,312] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-01-01 00:00:00+00:00
[2022-05-02 09:20:56,321] {standard_task_runner.py:52} INFO - Started process 3580 to run task
[2022-05-02 09:20:56,329] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '1037', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpcsxeyffi', '--error-file', '/tmp/tmpjy6o0f3d']
[2022-05-02 09:20:56,332] {standard_task_runner.py:77} INFO - Job 1037: Subtask local_to_gcs_task
[2022-05-02 09:20:56,711] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [running]> on host 98c324cf1bb6
[2022-05-02 09:20:56,954] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 09:20:57,143] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2022-05-02 09:20:58,209] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 09:20:58,310] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20210101T000000, start_date=20220502T092056, end_date=20220502T092058
[2022-05-02 09:20:58,378] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 09:20:58,593] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 16:02:02,141] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:02:02,193] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:02:02,195] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:02:02,197] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 16:02:02,198] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:02:02,249] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-01-01 00:00:00+00:00
[2022-05-02 16:02:02,259] {standard_task_runner.py:52} INFO - Started process 2722 to run task
[2022-05-02 16:02:02,267] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '1138', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmppj5zgo7y', '--error-file', '/tmp/tmp39e21kyp']
[2022-05-02 16:02:02,270] {standard_task_runner.py:77} INFO - Job 1138: Subtask local_to_gcs_task
[2022-05-02 16:02:02,668] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [running]> on host 9f5021834e17
[2022-05-02 16:02:02,939] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 16:02:03,126] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2022-05-02 16:02:03,903] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 16:02:04,026] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20210101T000000, start_date=20220502T160202, end_date=20220502T160204
[2022-05-02 16:02:04,155] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 16:02:04,447] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 16:37:48,531] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:37:48,573] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:37:48,575] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:37:48,576] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 16:37:48,577] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:37:48,616] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-01-01 00:00:00+00:00
[2022-05-02 16:37:48,627] {standard_task_runner.py:52} INFO - Started process 7357 to run task
[2022-05-02 16:37:48,634] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '1245', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmp6b0yzibl', '--error-file', '/tmp/tmplw28andy']
[2022-05-02 16:37:48,637] {standard_task_runner.py:77} INFO - Job 1245: Subtask local_to_gcs_task
[2022-05-02 16:37:49,018] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [running]> on host 9f5021834e17
[2022-05-02 16:37:49,289] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 16:37:49,507] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2022-05-02 16:37:50,256] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 16:37:50,367] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20210101T000000, start_date=20220502T163748, end_date=20220502T163750
[2022-05-02 16:37:50,431] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 16:37:50,661] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 16:52:47,452] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:52:47,501] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:52:47,502] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:52:47,504] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 16:52:47,505] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:52:47,544] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2021-01-01 00:00:00+00:00
[2022-05-02 16:52:47,554] {standard_task_runner.py:52} INFO - Started process 10130 to run task
[2022-05-02 16:52:47,561] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2021-01-01T00:00:00+00:00', '--job-id', '1349', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpbfx0hf9y', '--error-file', '/tmp/tmpm8kch2cq']
[2022-05-02 16:52:47,564] {standard_task_runner.py:77} INFO - Job 1349: Subtask local_to_gcs_task
[2022-05-02 16:52:47,939] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2021-01-01T00:00:00+00:00 [running]> on host 9f5021834e17
[2022-05-02 16:52:48,193] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 16:52:48,384] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T00:00:00+00:00
[2022-05-02 16:52:49,215] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 16:52:49,369] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20210101T000000, start_date=20220502T165247, end_date=20220502T165249
[2022-05-02 16:52:49,450] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 16:52:49,667] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
