[2022-04-28 06:05:50,784] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-04-28 06:05:50,831] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-04-28 06:05:50,833] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 06:05:50,834] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-28 06:05:50,836] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 06:05:50,888] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2003-01-01 00:00:00+00:00
[2022-04-28 06:05:50,899] {standard_task_runner.py:52} INFO - Started process 1912 to run task
[2022-04-28 06:05:50,907] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2003-01-01T00:00:00+00:00', '--job-id', '538', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpevcag1l4', '--error-file', '/tmp/tmpp2bredej']
[2022-04-28 06:05:50,910] {standard_task_runner.py:80} INFO - Job 538: Subtask local_to_gcs_task
[2022-04-28 06:05:51,330] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [running]> on host d4721d223bdd
[2022-04-28 06:05:51,818] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-28 06:05:52,049] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2003-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2003-01-01T00:00:00+00:00
[2022-04-28 06:05:53,663] {python.py:175} INFO - Done. Returned value was: None
[2022-04-28 06:05:53,779] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20030101T000000, start_date=20220428T060550, end_date=20220428T060553
[2022-04-28 06:05:53,852] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-28 06:05:54,121] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-04-29 02:36:26,041] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-04-29 02:36:26,081] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-04-29 02:36:26,083] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 02:36:26,085] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-29 02:36:26,086] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 02:36:26,127] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2003-01-01 00:00:00+00:00
[2022-04-29 02:36:26,136] {standard_task_runner.py:52} INFO - Started process 5502 to run task
[2022-04-29 02:36:26,145] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2003-01-01T00:00:00+00:00', '--job-id', '716', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpe4i88vm1', '--error-file', '/tmp/tmpjvh4on1j']
[2022-04-29 02:36:26,147] {standard_task_runner.py:80} INFO - Job 716: Subtask local_to_gcs_task
[2022-04-29 02:36:26,518] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [running]> on host 6fd0ba274d58
[2022-04-29 02:36:26,767] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-29 02:36:26,965] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2003-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2003-01-01T00:00:00+00:00
[2022-04-29 02:36:28,328] {python.py:175} INFO - Done. Returned value was: None
[2022-04-29 02:36:28,678] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20030101T000000, start_date=20220429T023626, end_date=20220429T023628
[2022-04-29 02:36:28,769] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-29 02:36:29,014] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-02 07:55:02,274] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-05-02 07:55:02,326] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-05-02 07:55:02,328] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 07:55:02,330] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 07:55:02,331] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 07:55:02,381] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2003-01-01 00:00:00+00:00
[2022-05-02 07:55:02,391] {standard_task_runner.py:52} INFO - Started process 9350 to run task
[2022-05-02 07:55:02,405] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2003-01-01T00:00:00+00:00', '--job-id', '862', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpdi0kdyzl', '--error-file', '/tmp/tmp9p50uh6d']
[2022-05-02 07:55:02,409] {standard_task_runner.py:77} INFO - Job 862: Subtask local_to_gcs_task
[2022-05-02 07:55:02,978] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [running]> on host ae42322ae538
[2022-05-02 07:55:03,246] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 07:55:03,453] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2003-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2003-01-01T00:00:00+00:00
[2022-05-02 07:55:04,262] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 07:55:04,402] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20030101T000000, start_date=20220502T075502, end_date=20220502T075504
[2022-05-02 07:55:04,586] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 07:55:04,824] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 09:17:06,765] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-05-02 09:17:06,811] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-05-02 09:17:06,813] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 09:17:06,814] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 09:17:06,816] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 09:17:06,864] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2003-01-01 00:00:00+00:00
[2022-05-02 09:17:06,874] {standard_task_runner.py:52} INFO - Started process 2619 to run task
[2022-05-02 09:17:06,883] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2003-01-01T00:00:00+00:00', '--job-id', '981', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmp8px2s10s', '--error-file', '/tmp/tmputim0y_b']
[2022-05-02 09:17:06,886] {standard_task_runner.py:77} INFO - Job 981: Subtask local_to_gcs_task
[2022-05-02 09:17:07,263] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [running]> on host 98c324cf1bb6
[2022-05-02 09:17:07,525] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 09:17:07,715] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2003-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2003-01-01T00:00:00+00:00
[2022-05-02 09:17:09,283] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 09:17:09,390] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20030101T000000, start_date=20220502T091706, end_date=20220502T091709
[2022-05-02 09:17:09,466] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 09:17:09,687] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 15:58:17,967] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-05-02 15:58:18,019] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-05-02 15:58:18,022] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 15:58:18,024] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 15:58:18,026] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 15:58:18,079] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2003-01-01 00:00:00+00:00
[2022-05-02 15:58:18,089] {standard_task_runner.py:52} INFO - Started process 1768 to run task
[2022-05-02 15:58:18,098] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2003-01-01T00:00:00+00:00', '--job-id', '1083', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpliyfep7l', '--error-file', '/tmp/tmp3n7snscv']
[2022-05-02 15:58:18,101] {standard_task_runner.py:77} INFO - Job 1083: Subtask local_to_gcs_task
[2022-05-02 15:58:18,468] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [running]> on host 9f5021834e17
[2022-05-02 15:58:18,705] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 15:58:18,903] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2003-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2003-01-01T00:00:00+00:00
[2022-05-02 15:58:19,656] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 15:58:19,814] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20030101T000000, start_date=20220502T155817, end_date=20220502T155819
[2022-05-02 15:58:19,889] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 15:58:20,107] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 16:33:19,706] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:33:19,758] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:33:19,761] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:33:19,763] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 16:33:19,765] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:33:19,822] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2003-01-01 00:00:00+00:00
[2022-05-02 16:33:19,836] {standard_task_runner.py:52} INFO - Started process 6333 to run task
[2022-05-02 16:33:19,844] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2003-01-01T00:00:00+00:00', '--job-id', '1190', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmp8gbjlr1i', '--error-file', '/tmp/tmpk16el18g']
[2022-05-02 16:33:19,850] {standard_task_runner.py:77} INFO - Job 1190: Subtask local_to_gcs_task
[2022-05-02 16:33:20,265] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [running]> on host 9f5021834e17
[2022-05-02 16:33:20,590] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 16:33:20,805] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2003-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2003-01-01T00:00:00+00:00
[2022-05-02 16:33:21,608] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 16:33:21,757] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20030101T000000, start_date=20220502T163319, end_date=20220502T163321
[2022-05-02 16:33:21,875] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 16:33:22,126] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 16:48:46,639] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:48:46,680] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [queued]>
[2022-05-02 16:48:46,681] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:48:46,682] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 16:48:46,683] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 16:48:46,726] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2003-01-01 00:00:00+00:00
[2022-05-02 16:48:46,736] {standard_task_runner.py:52} INFO - Started process 9139 to run task
[2022-05-02 16:48:46,743] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'local_to_gcs_task', 'scheduled__2003-01-01T00:00:00+00:00', '--job-id', '1293', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpms4pakeo', '--error-file', '/tmp/tmpuhz9s9rt']
[2022-05-02 16:48:46,746] {standard_task_runner.py:77} INFO - Job 1293: Subtask local_to_gcs_task
[2022-05-02 16:48:47,113] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.local_to_gcs_task scheduled__2003-01-01T00:00:00+00:00 [running]> on host 9f5021834e17
[2022-05-02 16:48:47,359] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 16:48:47,543] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2003-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2003-01-01T00:00:00+00:00
[2022-05-02 16:48:48,315] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 16:48:48,450] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=local_to_gcs_task, execution_date=20030101T000000, start_date=20220502T164846, end_date=20220502T164848
[2022-05-02 16:48:48,538] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 16:48:48,759] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
